// this fetches the openapi spec from the Chatterbox TTS api and generates Typescript types

// Usage:
//     CHATTERBOX_API_URL=https://my-api-url

// Or with .env file:
//     npm run sync-api

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

import "dotenv/config";
import openapiTS, { astToString } from "openapi-typescript";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUTPUT_PATH = path.resolve(__dirname, "../src/types/chatterbox-api.d.ts");

async function main() {
  const apiUrl = process.env.CHATTERBOX_API_URL;

  if (!apiUrl) {
    console.error("Error: CHATTERBOX_API_URL environment variable is not set.");
    process.exit(1);
  }

  const openApiUrl = `${apiUrl}/openapi.json`;
  console.log("Fetching OpeniAPI spec from: ", openApiUrl);

  const ast = await openapiTS(new URL(openApiUrl));
  const contents = astToString(ast);

  // Ensure output directory exists
  const outputDir = path.dirname(OUTPUT_PATH);

  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  // Add header comment
  const headerComment = `/** 
    * This file is auto-generated by scripts/sync-api.ts from ${openApiUrl}.
    * Do not edit this file directly. Run \`npm run sync-api\` to regenerate.
    *
    * Generated on: ${new Date().toISOString()}
**/
`;

  fs.writeFileSync(OUTPUT_PATH, headerComment + contents);
  console.log("Types written at: ", OUTPUT_PATH);
}

main();
